### ISSUE TITLE
I encountered the following error when running, what is going on?

### ISSUE THREAD

**Issue by dante1024** [lartpang/ZoomNet#16]
I encountered the following error when running, what is going on?

Traceback (most recent call last):
  File "main.py", line 355, in <module>
    main()
  File "main.py", line 340, in main
    model_ema = training(model=model, cfg=cfg)
  File "main.py", line 204, in training
    probs, loss, loss_str = model(
  File "/home/nls1/anaconda3/envs/zjb4/lib/python3.8/site-packages/torch/nn/modules/module.py", line 889, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/data/zjb/camo/ZoomNet-main/methods/module/base_model.py", line 19, in forward
    results = self.train_forward(*args, **kwargs)
  File "/data/zjb/camo/ZoomNet-main/methods/zoomnet/zoomnet.py", line 224, in train_forward
    output = self.body(
  File "/data/zjb/camo/ZoomNet-main/methods/zoomnet/zoomnet.py", line 199, in body
    l_trans_feats = self.encoder_translayer(l_scale)
  File "/data/zjb/camo/ZoomNet-main/methods/zoomnet/zoomnet.py", line 195, in encoder_translayer
    trans_feats = self.translayer(en_feats)
  File "/home/nls1/anaconda3/envs/zjb4/lib/python3.8/site-packages/torch/nn/modules/module.py", line 889, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/data/zjb/camo/ZoomNet-main/methods/zoomnet/zoomnet.py", line 47, in forward
    assert isinstance(xs, (tuple, list))
AssertionError

**Comment by lartpang** [comment]
@dante1024 
Did you modify any other code in our model?

**Comment by dante1024** [comment]
> @dante1024 Did you modify any other code in our model?

我实验室的服务器没办法连外网，模型里面就没办法去github下载resnet50，所以我用自己电脑先下载好预训练的resnet50，再上传到服务器，最后把模型里面resnet50的那部分直接加载上传的resnet50，然后就会报这个错了

**Comment by lartpang** [comment]
@dante1024 

这部分的错误意味着你的encoder部分没有输出一个列表。
你使用的是timm提供的模型么？

**Comment by dante1024** [comment]
> @dante1024
> 
> 这部分的错误意味着你的encoder部分没有输出一个列表。 你使用的是timm提供的模型么？

是的，我是用from timm.models import resnet50引入的resnet50，然后加载上传的预训练模型，按理说这样应该没问题

**Comment by lartpang** [comment]
从这个 https://github.com/lartpang/ZoomNet/issues/19 issue来看，你或许已经解决了这个问题 😄

**Comment by dante1024** [comment]
> 从这个 #19 issue来看，你或许已经解决了这个问题 😄

是的，您关闭吧，谢谢您的解答
